Full implementation
Kros-sk/Kros.Ocelot.ETagCaching pull request #2
Opened 2024-03-22 14:14 UTC by Burgyn

2024-03-28 12:02 UTC, majco333 approved these changes

2024-04-02 08:07 UTC, satano requested changes

2024-04-03 13:22 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/ETagCachePolicyBuilder.cs
> +    internal ETagCachePolicyBuilder(bool excludeDefaultPolicy = false)
To ako si to predstavujem je presne tak ako to popisuješ. 99% (vymyslené číslo 😉) prípadov je o tom, že používam default policy, ktorej budem pridávať `TagTemplates`. Tá možnosť bez "default" je tam hlavne pre prípad, že v niektorom prípade budeme potrebovať niečo úplne iné.

2024-04-03 13:29 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/ETagCachingMiddleware.cs
> +            policy = _cachingOptions.Value.GetPolicy(route.CachePolicy);
Ak nebudeš silno tlačiť na tvoje riešenie, tak by som rád ostal pri tomto riešení.
Je to síce možno trochu overkill, ale za mňa to výrazne zjednoduší implementáciu. Nemusím na niečo myslieť, nemusím robiť rozhodovanie či niečo áno alebo nie. ...

Viem, že na úrovni famerworkov sa takéto optimalizácie zvyknú robiť, aby to bolo pre koncového vývojára čo najefektívnejšie. Ale ja by som tu uprednostnil tú priamočiarosť. Teda aspoň podľa mňa je to priamočiarejšie.

2024-04-04 05:44 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/ETagCachingOptions.cs
> +        string policyName,
Nemá. Opravujem.

2024-04-04 05:44 UTC, Burgyn commented on README.md
>              p.TagTemplates("product:{tenantId}:{id}", "tenant:{tenantId}:all", "all");
Pridal som tam taký ľahký popis.

2024-04-04 06:07 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/Policies/TagTemplatesPolicy.cs
> +            var tag = new StringBuilder(tagTemplate);
👍

2024-04-04 06:10 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/Policies/CacheEntryExtraPropsPolicy.cs
> +internal sealed class CacheEntryExtraPropsPolicy(IEnumerable<KeyValuePair<string, object>> extraProps)
Neviem čo mi šlo vtedy hlavou 🤔

2024-04-04 06:37 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/Policies/EnableCachePolicy.cs
> +internal sealed class EnableCachePolicy : IETagCachePolicy
Máš pravdu. Zabudol som ju pridať do buildera.

Ona v princípe slúži na disablovanie policies ak by boli pridané nejak hromadne a človek ju chce pre špecificky endpoint zrušiť. Ale toto nepredpokladám, že sa bude používať.
Pridal som to do buildera a nechávam to zatiaľ tam.

2024-04-04 12:36 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/Policies/HttpHeadersHelper.cs
> +internal static class HttpHeadersHelper
fixed

2024-04-04 12:37 UTC, Burgyn commented on src/Kros.Ocelot.ETagCaching/Policies/DefaultPolicy.cs
> +        AddCacheHeaders(context.CachedResponseHeaders,context.ETag.ToString());
fixes

2024-04-04 13:36 UTC, satano approved these changes

2024-04-04 13:37 UTC, merged